version: "3.9"

services:
  ppiyong-app:
    image: ${ECR_URI}/ppiyong:latest

    container_name: ppiyong-chatbot

    volumes:
      - ./rag_data:/ppiyong-chatbot/rag_data
      - ./chroma_db:/ppiyong-chatbot/chroma_db

    ports:
      - "8000:8000"

    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped